name: Scheduled SERP Scraper

on:
  schedule:
    - cron: '12 12 * * 2'  # Runs daily at 18:20 UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run scraper
        run: |
          mkdir -p scraper_results
          python scraper.py

      - name: Move CSV to folder
        run: |
          mv search_results.csv scraper_results/$(date +"%Y-%m-%d")_search_results.csv

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add scraper_results/
          git commit -m "Add scraper results for $(date +"%Y-%m-%d")"
          git push
